language: python

services:
  - postgresql

python:
  - 3.6

install:
  - pip install -r examples/pipeline/intermediate/requirements.txt
  - pip install -r requirements.txt
  - bash sample_package.sh
  - pip install .[all]

before_script:
  - psql -c 'create database db;' -U postgres

script:
  - pytest

after_success: coveralls
