language: python

services:
  - postgresql

python:
  - 3.5
  - 3.6
  - 3.7

install:
  # CONDA INSTALL STARTS
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # CONDA INSTALL ENDS

  # Create a conda env with the current travis python version
  - conda create -q -n conda-env python=$TRAVIS_PYTHON_VERSION
  - conda activate conda-env

  # Test vanilla installation, make sure core clients are importable
  - pip install .
  - python -c 'import ploomber'
  - python -c 'import ploomber.tasks'
  - python -c 'import ploomber.products'
  - python -c 'import ploomber.clients'

  # install requirements
  - pip install -r examples/pipeline/intermediate/requirements.txt
  - pip install -r requirements.txt
  - pip install .[test]

  # install R and IR kernel
  - conda install -y r-base r-irkernel
  - echo "IRkernel::installspec()" | Rscript -

  # install sample package for tests
  - bash test_pkg.sh



before_install:
  - sudo apt-get -y install graphviz

before_script:
  - psql -c 'create database db;' -U postgres

script:
  - pytest  --cov=ploomber -v

after_success: coveralls
