language: python

python:
  - 3.6

install:
  - pip install -r examples/pipeline/intermediate/requirements.txt
  - pip install -r requirements.txt
  - bash sample_package.sh
  - pip install .[all]

script:
  - pytest

after_success: coveralls
