name: ploomber-docs

channels:
  - conda-forge

dependencies:
  - python=3.8
  - tree
  - pip
  - pip:
    # needed for the examples
    - joblib
    - scikit-learn
    - seaborn
    - psycopg2
    # for some reason, read the docs command to install the package fails due to
    # a version mismatch (it uses the setup.py file directly instead of pip),
    # adding this to fix it - we are now using the readthedocs.yaml for config
    # (as opposed to the website) which lets us install using pip-
    # this might no longer be necessary
    - Pygments==2.5.2
    - mistune<2

    # for converting notebooks
    - nbsphinx

    # for plotting
    - pygraphviz

    # for running notebooks from the projects repo
    - papermill
    - jupytext

    # has a function to orchestrate execution of notebook examples
    - git+https://github.com/ploomber/projects.git#subdirectory=pkg