# Commonly used commands:

# To build the pipeline:
#     $ ploomber entry pipeline.yaml
#
# To start an interactive session (use "dag" variable when it starts):
#     $ ipython -i -m ploomber.entry pipeline.yaml -- --action status

meta:
  [% if db -%]
  product_default_class:
    # replace for GenericSQLRelation, SQLiteRelation or PostgresRelation
    # it you want to save metadata (required for incremental builds)
    SQLScript: SQLRelation
  [% endif %]
  # inspect source code to extract upstream dependencies
  extract_upstream: True

  # do not inspect source code to extract product (declare them here)
  extract_product: False

[% if db -%]
clients:
  SQLScript: db.get_client
[% endif %]

tasks:
  # list tasks here
  - source: clean.py
    name: clean
    product:
      nb: output/clean.ipynb
      data: output/clean.csv

  - source: plot.py
    name: plot
    product: output/plot.html
